### ISSUE TITLE
enable on Firefox Marketplace for Android

### ISSUE THREAD

**Issue by jancborchardt** [owncloud-archive/news-mobile#10]
When browsing marketplace.firefox.com from an Android tablet or smartphone the app is not findable.

Check yourself by searching https://marketplace.firefox.com/search?q=owncloud from an Android device.

You should enable it in the app settings to be available on all platforms. :)

**Comment by ilijalazarevic** [comment]
I haven't tried that, but packing application for FF OS and Android is different, so I guess Android would need special type of package. That would involve PhoneGap building and deploying result as Android application. FF OS application is basically a zip package with html5/js/css as content.

**Comment by jancborchardt** [comment]
I guess you misunderstood my remark. Firefox OS apps are also installable on Android devices. To do that, you just need to browse the Marketplace from an Android device and install it through there. It’s still simple html5/css/js apps, but they have an icon on the home screen then.

It doesn’t require any different packaging. You just need to go in the app dashboard on firefox marketplace, look for where to set which devices this app should run on and flip the switch so that ownCloud News is also available on Android.

**Comment by ilijalazarevic** [comment]
I can't access that option.
