### ISSUE TITLE
Porting application to Android using PhoneGap

### ISSUE THREAD

**Issue by ilijalazarevic** [owncloud-archive/news-mobile#12]
I've been trying in past few days to make this application work on Android using PhoneGap/Cordova.

Since angular-seed project with slight tweaks works just fine, I tried the same steps described here http://projectpoppycock.com/angularjs-phonegap-and-angular-seed-lets-go/.

Main problem with mine approach, as same as few similar which I did, is that links which point to locations outside of application open in same window instead of opening in system browser.

The steps given at given link work as they should, but this application with all that changes just doesn't work the same regarding following links to outside addresses.

@Raydiation

**Comment by BernhardPosselt** [comment]
Shouldnt a target="_blank" solve this?

**Comment by ilijalazarevic** [comment]
Well, it works in Firefox OS and desktop browsers, but on Android it just opens link in the same window where application is running. Target doesn't seem to affect it.

**Comment by BernhardPosselt** [comment]
Try http://stackoverflow.com/questions/14070841/phonegap-open-link-in-browser

**Comment by ilijalazarevic** [comment]
Thanks, I'll try it. It seems that access origin tag in PhoneGap's config.xml would suffice, but it blocks AJAX requests.

**Comment by ilijalazarevic** [comment]
This is successfully finished with calling 

```
window.open(url, "_system");
```

which should work the same on all platforms.
