### ISSUE TITLE
publish on Firefox Marketplace

### ISSUE THREAD

**Issue by jancborchardt** [owncloud-archive/news-mobile#2]
Would be cool to have the app published on the Firefox Marketplace to be able to install it on Firefox OS devices. What’s the current state of the app?

cc @ikacikac @Raydiation

**Comment by ilijalazarevic** [comment]
I'm interested in community feedback, maybe some web design contribution to spice it up. Also, I'd like to hear about someone actually trying to use it on simulator, and their thoughts. Building package is a procedure I've already done, and package install is working well.

**Comment by jancborchardt** [comment]
@ikacikac I’m not sure how much time I have regarding design help. I suggest you use Bootstrap to get a good working responsive design: http://getbootstrap.com

**Comment by jancborchardt** [comment]
@ikacikac oh ok, you already use that. Can you update to Bootstrap v3?

**Comment by jancborchardt** [comment]
@ikacikac also, it already looks and works good for a first deploy to the Firefox Marketplace I would say. Can you do that? Best use »ownCloud News« as name. :)

**Comment by ilijalazarevic** [comment]
@jancborchardt Concerning Bootstrap v3, I'm not into web design too much, and this is my first time using Bootstrap, but I think that adopting it would not be a big job.

**Comment by ilijalazarevic** [comment]
I'd like to point out that some things were done on beginner level (implementing Bootstrap driven responsive design), and like a quick patches to get the things started. More Q and proposals for dealing with potential problems would be very useful.

**Comment by ilijalazarevic** [comment]
Since I didn't have enough time for familiarizing with new bootstrap, I have posted current version of application on Firefox Marketplace as a smart phone Firefox OS application. It is in queue, and should be reviewed in few days.

**Comment by ilijalazarevic** [comment]
First public version of ownCloud News application for Firefox OS has been approved, and it is publicly available at https://marketplace.firefox.com/app/owncloudnews/

**Comment by cosenal** [comment]
Why is this open? Also, please remove my name from the authors (in the marketplace too). I haven't written a single line of this app.

**Comment by jancborchardt** [comment]
Also, why is the layout so radically different from the actual News app? Couldn't it just be the same?

**Comment by ilijalazarevic** [comment]
@cosenal Done.
@jancborchardt No particular reason. I'm not very experienced with frontend development :) Some help in that field would be appreciated.

I'd like to close this, and if there is need for continuing about layout, we can open an enhancement issue for that.
