### ISSUE TITLE
www subfolder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud-archive/news-mobile#3]
It’s quite strange that everything is in a »www« subfolder. Should be moved out of that so that it’s the root. @ikacikac

**Comment by ilijalazarevic** [comment]
Well I have used what was already there. I think there is no problem with moving some folders.

**Comment by ilijalazarevic** [comment]
There is a nice structure which generator-angular impose, maybe accepting it as good practice wouldn't be bad.

**Comment by BernhardPosselt** [comment]
www is the common folder for phonegap where the webapp is in. The other subfolders with plattform specifc code are not there yet

**Comment by ilijalazarevic** [comment]
I'm interested if some utility needed folders from www/ should be moved one level up. Particularly node_modules/ folder, because PhoneGap is including it in Android app which then weights about 40 MB :( @Raydiation

**Comment by BernhardPosselt** [comment]
Sure go ahead. I think you just want to move the build stuff to the top level and adjust the paths
